version: "2.28"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
